# See: https://www.mkdocs.org/user-guide/configuration/

# Site configuration:
site_name: Dogma
site_author: Arto Bendiken
site_url: https://dogma.dev
repo_name: dogmatists/dogma.dev
repo_url: https://github.com/dogmatists/dogma.dev
google_analytics:

# Content configuration:
remote_name: github
docs_dir: content
site_dir: public
use_directory_urls: false

# Table of contents (TOC):
nav:
  - Introduction: index.md
  - Installation: install.md
  - Getting Started: start.md
  - Concepts: concepts.md
  - Tutorials: learn.md
  - FAQs: faq.md
  - Release Notes: history.md
  - Glossary: glossary.md
  - License: license.md
  - Reference:
    - Angle: Angle.md
    - Latitude: Latitude.md
    - Longitude: Longitude.md

# Theme configuration:
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

# Markdown configuration:
markdown_extensions:
  - admonition

# Plugin configuration:
plugins:
  - search
  - macros
  - mermaid2:
      arguments:
        theme: neutral

# Custom CSS configuration:
extra_css:
  - css/extra.css

# Custom JS configuration:
extra_javascript:
  - https://unpkg.com/mermaid@8.5.2/dist/mermaid.min.js  # Mermaid plugin
  - js/extra.js
