# See: https://www.mkdocs.org/user-guide/configuration/
---
# Site configuration:
site_name: Dogma
site_author: Arto Bendiken
site_url: https://dogma.dev
repo_name: dogmatists/dogma.dev
repo_url: https://github.com/dogmatists/dogma.dev
google_analytics:
  - UA-83574-22
  - auto

# Content configuration:
remote_name: github
docs_dir: content
site_dir: public
use_directory_urls: false

# Table of contents (TOC):
nav:
  - Introduction: index.md
  - Installation: install.md
  - Getting Started: start.md
  - Concepts: concepts.md
  - Tutorials: learn.md
  - FAQs: faq.md
  - Release Notes: history.md
  - Glossary: glossary.md
  - License: license.md
  - Languages:
      - C: c/README.md
      - C++: cpp/README.md
      - Dart: dart/README.md
      - Protobuf: protobuf/README.md
      - Python: python/README.md
      - Ruby: ruby/README.md
      - Rust: rust/README.md
      - Zig: zig/README.md
  - Reference:
      - Angle: Angle.md
      - Latitude: Latitude.md
      - Location: Location.md
      - Longitude: Longitude.md

# Theme configuration:
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

# Markdown configuration:
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

# Plugin configuration:
plugins:
  - search
  - macros
  - mermaid2:
      arguments:
        theme: neutral

# Custom CSS configuration:
extra_css:
  - css/extra.css

# Custom JS configuration:
extra_javascript:
  - https://unpkg.com/mermaid@8.5.2/dist/mermaid.min.js  # Mermaid plugin
  - js/extra.js

# Footer configuration:
extra:
  social:
    - name: Dogma on GitHub
      icon: fontawesome/brands/github
      link: https://github.com/dogmatists
    - name: Dogma on GitLab
      icon: fontawesome/brands/gitlab
      link: https://gitlab.com/dogmatists
    - name: Dogma on Bitbucket
      icon: fontawesome/brands/bitbucket
      link: https://bitbucket.org/dogmatists
    - name: Dogma on Stack Overflow
      icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/questions/tagged/dogma
    - name: Dogma on Twitter
      icon: fontawesome/brands/twitter
      link: https://twitter.com/bendiken
