# See: https://dart.dev/tools/pub/pubspec
name: dogma
version: 0.0.2
description: >-
  Dogma for Dart.
homepage: https://github.com/dogmatists/dogma.dart
repository: https://github.com/dogmatists/dogma.dart
issue_tracker: https://github.com/dogmatists/dogma.dart/issues
documentation:
dependencies:
  meta: ^1.1.8
dev_dependencies:
  pedantic: ^1.9.2
  test: any
dependency_overrides:
environment:
  sdk: '>=2.8.1 <3.0.0'
executables:
